#!/bin/bash 
set -x

charge=$(acpi | cut -b 12-19)

echo $charge

warn () {
  if [ $percentage -eq 15 ] 
  then
    notify-send -u normal "low battery: battery at 15%"
  elif [ $percentage -le 5 ]
  then 
    notify-send -u critical "5% or lower remaining \nplease plug in your device or suspend immediately!"
    notify-send -u critical "WARNING: LOW BATTERY"
  fi
}

bat=/sys/class/power_supply/BAT1/capacity

while true 
do
  while read percentage
  do
    if [ "$charge" != "Charging" ]
    then
      warn
    elif [ "$charge" == "Charging" ]
    then
      sleep
    fi
  done < $bat
  sleep 180
done

