#!/bin/bash

url='https://duckduckgo.com/?q='

query=$(echo '' | dmenu -p 'Search: ' -nb '#eeeeee' -nf '#4d4d4c' -sb '#3e999f' -fn 'DejaVuSansMono')

if [ -n "$query" ]; then
    surf "$url""$query"
fi
